[package]
name = "mos-core"
version = "0.0.0" # unused
authors = ["Roy Jacobs <roy.jacobs@gmail.com>"]
edition = "2024"
repository = "https://github.com/datatrash/mos"
license = "MIT"
keywords = ["retro", "6502", "assembler"]

[lib]

[dependencies]
bitflags = "2"
codespan-reporting = "0.13"
fs-err = "3"
indexmap = "2.14"
itertools = "0.15"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_info"] }
nom = "8"
nom_locate = "5"
once_cell = "1.21"
path-absolutize = "4"
path-dedot = "4"
pathdiff = "0.2"
petgraph = "0.8"
serde = { version = "1", features = ["derive"] }
smallvec = "1"
strum = { version = "0.28", features = ["derive"] }

[dev-dependencies]
mos-testing = { path = "../mos-testing" }
tempfile = "3"
